message = input('Digite algo: ')
print('O tipo primitivo da mensagem {} é: {}'.format(message, type(message)))
print('Só tem espaços? {}'.format(message.isspace()))
print('É um número? {}'.format(message.isnumeric()))
print('É alfabético? {}'.format(message.isalpha()))
print('É alfanumérico? {}'.format(message.isalnum()))
print('Está em maiúsculas? {}'.format(message.isupper()))
print('Está em minúsculas? {}'.format(message.islower()))
print('Está capitalizada? {}'.format(message.istitle()))